apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  labels:
    app: fortune-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: boot
  selector:
    app: fortune-app
  type: ClusterIP
